services:
  frontend:
    container_name: kupi-fronten
    image: okokanya/kupi-frontend-optima:1.0.0-alpine
    restart: always
    ports:
      - 8080:80
    networks:
      - external

  backend:
    container_name: kupi-backend
    image: okokanya/kupi-backend-optima:1.0.0-alpine
    restart: always
    env_file: .env
    ports:
      - 4000:3000
    networks:
      - internal

  database:
    container_name: postgres-database
    image: postgres:alpine
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/data/postgres
    networks:
      - internal

  adminer:
    container_name: postgres-preview
    image: adminer
    restart: always
    ports:
      - 5000:8080
    networks:
      - internal

volumes:
  postgres_data:


networks:
  internal:
  external:
